/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as assessments from "../assessments.js";
import type * as http from "../http.js";
import type * as mentorSignUpForm from "../mentorSignUpForm.js";
import type * as organization from "../organization.js";
import type * as organizationInvitation from "../organizationInvitation.js";
import type * as organizationMembership from "../organizationMembership.js";
import type * as user from "../user.js";
import type * as utils_builders from "../utils/builders.js";
import type * as utils_enhancers from "../utils/enhancers.js";
import type * as utils_validators from "../utils/validators.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  assessments: typeof assessments;
  http: typeof http;
  mentorSignUpForm: typeof mentorSignUpForm;
  organization: typeof organization;
  organizationInvitation: typeof organizationInvitation;
  organizationMembership: typeof organizationMembership;
  user: typeof user;
  "utils/builders": typeof utils_builders;
  "utils/enhancers": typeof utils_enhancers;
  "utils/validators": typeof utils_validators;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
